title: Site

tabs:

  # content tab
  content:
    label: Content
    icon: text
    preset: pages
    unlisted: true

  # seo tab
  seo:
    label: SEO
    icon: search
    fields:
      seoTitle:
        label: SEO Title
        type: text
      seoDescription:
        label: SEO Description
        type: markdown